name: 'Build and deploy Python app to Azure Web App: credit-check-app-2025'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write     # <-- REQUIRED for OIDC
  contents: read 

env:
  AZURE_WEBAPP_NAME: credit-check-app-2025
  AZURE_RESOURCE_GROUP: creditcheck-rg
  DJANGO_SETTINGS_MODULE: config.config.settings
  PYTHONPATH: .

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static (no manage.py path required)
        run: |
          python -m django collectstatic --noinput

      - name: Vendor site-packages for Azure
        run: |
          mkdir -p .python_packages/lib/site-packages
          pip install -r requirements.txt -t .python_packages/lib/site-packages

      - name: Create deploy artifact
        run: zip -r release.zip . -x ".git/*" ".github/*"

      - name: Deploy to Azure Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
              --name "${{ env.AZURE_WEBAPP_NAME }}" \
              --src-path release.zip \
              --type zip \
              --clean true \
              --restart true
