name: 'Build and deploy Python app to Azure Web App: credit-check-app-2025'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: credit-check-app-2025
  DJANGO_SETTINGS_MODULE: config.config.settings
  PYTHONPATH: .

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static (no manage.py path required)
        run: |
          python -m django collectstatic --noinput

      - name: Vendor site-packages for Azure
        run: |
          mkdir -p .python_packages/lib/site-packages
          pip install -r requirements.txt -t .python_packages/lib/site-packages

      - name: Create deploy artifact
        run: zip -r release.zip . -x ".git/*" ".github/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_b0c933e2562f42fba85e3bb12ca32c44 }}
          package: release.zip
